import mongoose from "mongoose";

// Sub-schema for the text chunks to support MongoDB Atlas Vector Search
const chunkSchema = new mongoose.Schema({
    chunkId: {
        type: String,
        required: true
    },
    text: {
        type: String,
        required: true
    },
    embedding: {
        type: [Number], // Dynamic array of floats generated by Gemini/Ollama
        required: true
    },
    metadata: {
        section: { type: String, default: "Main" },
        pageNumber: { type: Number, default: 1 }
    }
});

const paperSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true,
        trim: true
    },
    authors: {
        type: String,
        default: "Unknown"
    },
    abstract: {
        type: String,
        default: ""
    },
    pdfUrl: {
        type: String,
        required: true
    },
    globalDifficultyRating: {
        type: Number,
        default: 0.0,
        min: 0,
        max: 5
    },
    // The RAG Pipeline will push parsed text blocks and vectors here
    chunks: [chunkSchema]
}, { timestamps: true });

// Indexing title for basic keyword search performance
paperSchema.index({ title: "text", abstract: "text" });

const paperModel = mongoose.models.paper || mongoose.model('paper', paperSchema);
export default paperModel;